/// MCQ model matching the backend API schema
/// Includes option-specific explanations pre-generated by ChatGPT
class MCQOption {
  final String letter;
  final String text;

  MCQOption({
    required this.letter,
    required this.text,
  });

  factory MCQOption.fromJson(Map<String, dynamic> json) {
    return MCQOption(
      letter: json['letter'] as String,
      text: json['text'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'letter': letter,
      'text': text,
    };
  }
}

class MCQ {
  final String id;
  final String subject;
  final String stem; // Question text
  final List<MCQOption> options;
  final String correctOption; // Letter: 'A', 'B', 'C', 'D', or 'E'
  final String explanationCorrect; // Shown when user is correct
  final Map<String, String> explanationsByOption; // Per-option explanations
  final String difficulty; // 'easy', 'medium', 'hard'
  final String? sourceHint; // Optional topic tag

  MCQ({
    required this.id,
    required this.subject,
    required this.stem,
    required this.options,
    required this.correctOption,
    required this.explanationCorrect,
    required this.explanationsByOption,
    required this.difficulty,
    this.sourceHint,
  });

  factory MCQ.fromJson(Map<String, dynamic> json) {
    return MCQ(
      id: json['id'] as String,
      subject: json['subject'] as String,
      stem: json['stem'] as String,
      options: (json['options'] as List)
          .map((opt) => MCQOption.fromJson(opt as Map<String, dynamic>))
          .toList(),
      correctOption: json['correct_option'] as String,
      explanationCorrect: json['explanation_correct'] as String,
      explanationsByOption: Map<String, String>.from(
        json['explanations_by_option'] as Map,
      ),
      difficulty: json['difficulty'] as String,
      sourceHint: json['source_hint'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'subject': subject,
      'stem': stem,
      'options': options.map((opt) => opt.toJson()).toList(),
      'correct_option': correctOption,
      'explanation_correct': explanationCorrect,
      'explanations_by_option': explanationsByOption,
      'difficulty': difficulty,
      'source_hint': sourceHint,
    };
  }

  /// Get the correct answer text
  String get correctAnswerText {
    final option = options.firstWhere(
      (opt) => opt.letter == correctOption,
      orElse: () => options.first,
    );
    return option.text;
  }

  /// Get explanation for a specific option (for when user picks wrong answer)
  String getExplanationForOption(String letter) {
    return explanationsByOption[letter] ?? explanationCorrect;
  }

  /// Check if the given answer is correct
  bool isCorrect(String userAnswer) {
    return userAnswer == correctOption;
  }

  @override
  String toString() {
    return 'MCQ(id: $id, subject: $subject, difficulty: $difficulty)';
  }
}
